
public enum QueueingFunction {
	ENQUEUE_AT_FRONT, ENQUEUE_AT_END, SORTED_INSERT, ENQUEUE_AT_FRONT_WITH_LIMIT
	, ENQUEUE_GREEDY_HEURISTIC_ONE, ENQUEUE_GREEDY_HEURISTIC_TWO, ENQUEUE_A_HEURISTIC_ONE, ENQUEUE_A_HEURISTIC_TWO
}
